behaviors:
  MoveToGoal:
    trainer_type: ppo
    hyperparameters:
      batch_size: 
        opt_values: [256, 512, 1024]
      buffer_size: 
        opt_values: [10240, 20480, 40960]
      learning_rate: 3.0e-4
      beta: 0.001
      epsilon: 0.3
      lambd: 0.9
      num_epoch: 
        opt_values: [3, 6]
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
      
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
      
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          hidden_units: 512
          num_layers: 4
      curiosity:
        gamma: 0.85
        strength: 0.001
        network_settings:
          hidden_units: 512
          num_layers: 4
        learning_rate: 3.0e-4
        
    max_steps: 3000000
    time_horizon: 
      opt_values: [256, 512, 1024]
    summary_freq: 30000
    threaded: true
    
    opt_stop:
        tag: Environment/Cumulative Reward
        step: 600000
        min: 0