behaviors:
  MoveToGoal:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 3.0e-4
      beta: 1.0e-3
      epsilon: 0.3
      lambd: 0.9
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
      
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
      
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          hidden_units: 512
          num_layers: 4
      curiosity:
        gamma: 0.85
        strength: 1.0e-3
        network_settings:
          hidden_units: 512
          num_layers: 4
        learning_rate: 3.0e-4
        
    max_steps: 3000000
    time_horizon: 4096
    summary_freq: 30000
    threaded: true